* CONCEPT

  Our goal is to make an Emacs mode to edit not-so-bad in Java using only Elisp.
* Recommended configuration

Clone this repository and:

#+BEGIN_SRC elisp
(use-package java-mode-for-real
  :load-path "~/your/path/to/java-mode-for-real"
  :mode ("\\.java\\'" . jmr-mode)
  :bind (:map jmr-mode-map
              ("C-c C-c" . jmr-compile)
              ("C-c C-e" . jmr-execute)
              ("C-c C-r" . jmr-compile-execute)
              ("C-c C-m" . jmr-set-main)
              ("C-c C-a" . jmr-add-jar)
              ("C-c C-d" . jmr-delete-jar)
              ("C-c C-l" . jmr-list-jars)
              ("C-c C-t" . jmr-type-on-pointer)))
#+END_SRC

* How to use it!

* REASONABLE IDEAS

- [ ] "javap -cp <path.jar> package.to.Class" to get all the functions of the class
- [ ] Once we have all the knowdledge, autocomplete ^^
- [ ] Menus (https://github.com/jdee-emacs/jdee/blob/master/jdee.el#L972)
- [X] "jar tf <path.jar>" to get all classes and packages
- [X] Derivate project from java-mode. ([[https://www.gnu.org/software/emacs/manual/html_node/elisp/Derived-Modes.html#Derived-Modes][How to derive from a major mode]])
- [X] An auxiliar archive in the project folder to list used JARs, in order to create directly our classpath.
# - [ ] The java library preloaded?
- [X] "javac -cp pathjar1;pathjar2 Main.java" to compile? http://www.ntu.edu.sg/home/ehchua/programming/java/j9c_packageclasspath.html
- [X] "java -cp .;pathjar1;pathjar2 Main" to execute?

* Links
- https://github.com/jdee-emacs/jdee/blob/master/jcomplete.el
- https://github.com/skeeto/emacs-java/blob/master/java-mode-plus.el
* NOT-SO-REASONABLE IDEAS (now)

  - Create a tree with all project classes, showing relations and types of each one.
  - Debugger.
  - A Java flycheck-like mode.
